/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const before_Vehicle_Create_Update = require('./code/before-vehicle-create-update');
const after_Product_Read = require('./code/after-product-read');
const before_Scale_Create_Update = require('./code/before-scale-create-update');
const on_Weighing_Execute = require('./code/on-weighing-execute');
const on_Invoice_Issue = require('./code/on-invoice-issue');
const weighing_Logic = require('./code/weighing-logic');

class hack2BuildSrv extends LCAPApplicationService {
    async init() {

        this.before(['CREATE', 'UPDATE'], 'Vehicle', async (request) => {
            await before_Vehicle_Create_Update(request);
        });

        this.after('READ', 'Product', async (results, request) => {
            await after_Product_Read(results, request);
        });

        this.before(['CREATE', 'UPDATE'], 'Scale', async (request) => {
            await before_Scale_Create_Update(request);
        });

        this.on('execute', 'Weighing', async (request) => {
            return on_Weighing_Execute(request);
        });

        this.on('issue', 'Invoice', async (request) => {
            return on_Invoice_Issue(request);
        });

        this.after(['CREATE', 'DELETE', 'READ', 'UPDATE'], 'Weighing.drafts', async (results, request) => {
            await weighing_Logic(results, request);
        });

        return super.init();
    }
}


module.exports = {
    hack2BuildSrv
};